import type { Metadata } from "next";
import  { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./components/Navigation/ResponsiveNav";


//fonts styling

const barlow_condensed = Barlow_Condensed({
  weight:["300","400","500","600","700","800"],
  subsets:["latin"]
});

export const metadata: Metadata = {
  title: "Burger|junk food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow_condensed.className} ${barlow_condensed.className} antialiased`} >
          <ResponsiveNav />
        {children}
      </body>
    </html>
  );
}